add config
zhtttyl/zhTest pull request #3
Opened 2023-03-19 13:55 UTC by zhtttylz

add config

2023-06-02 11:07 UTC, zhtttyl reviewed
test

2023-06-02 11:10 UTC, zhtttyl requested changes
test-req-change

2023-06-02 11:12 UTC, zhtttyl approved these changes

2023-06-02 11:13 UTC, merged

2023-06-03 10:37 UTC, zhtttylz commented
> test

Thank you very much for your valuable suggestion